default:
    method: "hlt_stoch"
    max_steps: 200
    max_frames: 10000
    frame_skip: 2
    model_lr: !!float 3e-3
    policy_lr: !!float 3e-3
    value_lr: !!float 3e-4
    soft_q_lr: !!float 3e-4
    reward_scale: 1.0
    horizon: 5
    model_iter: 5
    trajectory_samples: 20
    lam: 0.1
    activation_fun: 'ReLU'

PendulumEnv:
    activation_fun: 'ReLU'
    max_frames: 10000
    frame_skip: 4
    max_steps: 200
    trajectory_samples: 60

AcrobotEnv:
    activation_fun: 'ReLU'
    max_frames: 10000
    frame_skip: 4
    max_steps: 500
    model_iter: 5

PendubotEnv:
    activation_fun: 'ReLU'
    max_frames: 10000
    frame_skip: 4
    max_steps: 500
    model_iter: 5

InvertedPendulumBulletEnv:
    activation_fun: 'sin'
    max_frames: 10000
    frame_skip: 4
    max_steps: 200
    lam: 0.1
    model_iter: 5

InvertedPendulumRoboschoolEnv:
    activation_fun: 'ReLU'
    max_frames: 50000
    frame_skip: 4
    max_steps: 1000
    horizon: 5
    lam: 0.1
    trajectory_samples: 60

HopperEnv:
    max_frames: 50000
    max_steps: 1000
    frame_skip: 4
    lam: 0.2
    trajectory_samples: 60

HalfCheetahEnv:
    max_frames: 50000
    max_steps: 1000
    frame_skip: 1
    lam: 0.2
    horizon: 10
    trajectory_samples: 60

PusherEnv:
    activation_fun: 'ReLU'
    max_frames: 50000
    max_steps: 100
    frame_skip: 2
    lam: 0.2
    trajectory_samples: 60
    horizon: 10
